server:
    port: 8761

eureka:
    instance:
        hostname: localhost2
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/