server:
    port: 9090


eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/


spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: eureka-client-service
                  uri: http://localhost:8082/
                  predicates:
                      - Path=/firstService/**
                - id: iotsense-api
                  uri: http://localhost:8094/
                  predicates:
                        - Path=/api/chartdata/**
            default-filters:
                - TokenRelay
    security:
        oauth2:
            client:
                provider:
                    my-keycloak-provider:
                        issuer-uri: http://localhost:8180/auth/realms/assetTech
                registration:
                    keycloak-spring-gateway-client:
                        provider: my-keycloak-provider
                        client-id: assetTechClient
                        client-secret: 422b5546-504f-453d-8bf9-0940c4159ccb
                        authorization-grant-type: authorization_code
                        redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'

